apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: prenom-dev
resources:
- ../../base
patches:
- patch-deployment.yaml
- patch-ingress.yaml
configMapGenerator:
- name: hello-world-config
  envs:
  - env.txt
secretGenerator:
- name: hello-world-secret
  envs:
  - secrets.txt
  type: Opaque
