---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prenom-hello-world
spec:
  replicas: 1
  template:
    spec:
      containers:
      - image: eu.gcr.io/formation-auchan/hello:latest
        name: helloworld
        envFrom:
        - configMapRef:
            name: hello-world-config
        - secretRef:
            name: hello-world-secret
