---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prenom-hello-world
spec:
  replicas: 2
  template:
    spec:
      containers:
      - image: eu.gcr.io/formation-auchan/hello:latest
        name: helloworld
        env:
        - name: MSG
          value: "Hello prenom from PROD !"
